---
new_page_extension: md
auto_deploy: true
admin_path: site/.forestry
webhook_url: 
sections:
- type: directory
  path: site/content/podcast
  label: Podcast
  create: all
  match: "**/*"
- type: directory
  path: site/content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.31.1
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.31.1
  preview_output_directory: public
  output_directory: public
version: 0.31.1
