baseURL                       = "/"
title                         = "FVCproductions"
metaDataFormat                = "yaml"
enableEmoji                   = true
footnoteReturnLinkContents    = "‚Ü©"

# Language
languageCode                  = "en-EN"
DefaultContentLanguage        = "en"

# Categories
preserveTaxonomyNames         = true
paginate                      = 5

# Code
pygmentsCodefences            = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle                 = "monokai"

# Internal Templates
googleAnalytics = "UA-63190978-3"
disqusShortname = "fvcproductions"

# RSS
[outputs]
    home = ["HTML", "AMP", "RSS"]
    page = ["HTML", "AMP"]

[outputFormats]
    [outputFormats.RSS]
        mediatype = "application/rss"
        baseName = "feed"

# Homepage
[params]
    headline                  = "Hey there, I'm Frances! üëãüèΩÔ∏è"
    description               = "I like to dabble with things that ought to be dabbled with. üçìÔ∏èÔ∏èüç´Ô∏è"
    copyright                 = "FVCproductions"
    year                      = 2013

# Permalinks
[permalinks]
  adventures                  = "/adventures/:year/:month/:day/:title/"

# Navigation Menu
[[menu.main]]
    name                      = "Home üè†"
    url                       = "/"
    weight                    = 1

[[menu.main]]
    name                      = "About üëÄ"
    url                       = "/about"
    weight                    = 2

[[menu.main]]
    name                      = "Adventures ‚úàÔ∏è"
    url                       = "/adventures"
    weight                    = 3

[[menu.main]]
    name                      = "Awards üèÜÔ∏è"
    url                       = "/awards"
    weight                    = 4

[[menu.main]]
   name                       = "Blog üìùÔ∏è"
   url                        = "/blog"
   weight                     = 5

[[menu.main]]
    name                      = "Contact üì®"
    url                       = "/contact"
    weight                    = 6

[[menu.main]]
    name                      = "Now üïíÔ∏è"
    url                       = "/now"
    weight                    = 7

[[menu.main]]
    name                      = "Portfolio üíº"
    url                       = "/portfolio"
    weight                    = 8

[[menu.main]]
    name                      = "Services üõ†Ô∏è"
    url                       = "/services"
    weight                    = 9

[[menu.main]]
    name                      = "Speaking üí¨Ô∏è"
    url                       = "/speaking"
    weight                    = 10

# Social Links
[social]
    angellist                 = "fvcproductions"
    behance                   = "fvcproductions"
    calendly                  = "fvcproductions"
    codepen                   = "fvcproductions"
    deviantart                = "fvcproductions"
    dribbble                  = "fvcproductions"
    email                     = "hello@fvcproductions.com"
    etsy                      = "fvcproductions"
    facebook                  = "fvcproductions"
    freecodecamp              = "fvcproductions"
    github                    = "fvcproductions"
    gitlab                    = "fvcproductions"
    googleplus                = "fvcproductions2013"
    hackernews                = "fvcproductions"
    houzz                     = "fvcproductions"
    instagram                 = "fvcproductions"
    linkedin                  = "fvcproductions"
    medium                    = "fvcproductions"
    meetup                    = "182920007"
    paypal                    = "fvcproductions"
    producthunt               = "fvcproductions"
    quora                     = "Frances-Coronel-1"
    reddit                    = "fvcproductions"
    scribd                    = "194063411/FVCproductions"
    slideshare                = "fvcproductions"
    soundcloud                = "fvcproductions"
    spotify                   = "fvcproductions"
    stackexchange             = "3595658/fvcproductions"
    stackoverflow             = "3000467/fvcproductions"
    steam                     = "fvcproductions"
    trello                    = "fvcproductions"
    tumblr                    = "fvcproductions2013"
    twitter                   = "fvcproductions"
    vimeo                     = "fvcproductions"
    youtube                   = "fvcproductions2013"