baseURL                       = "https://fvcproductions.com"
title                         = "FVCproductions"
metaDataFormat                = "yaml"
enableEmoji                   = true
footnoteReturnLinkContents    = "‚Ü©"

# Language
languageCode                  = "en-us"
defaultContentLanguage        = "en"

# Categories
preserveTaxonomyNames         = false

# Code
pygmentsCodefences            = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle                 = "manni"
# pygmentsOptions             = "linenos=table"

# Internal Templates
googleAnalytics               = "UA-63190978-3"
disqusShortname               = "fvcproductions"

# RSS
[outputs]
    home                      = ["HTML", "AMP", "RSS"]
    page                      = ["HTML", "AMP"]

[outputFormats]
    [outputFormats.RSS]
        mediatype             = "application/rss"
        baseName              = "feed"

# Homepage
[params]
    headline                  = "Hey there, I'm Frances! üëãüèΩÔ∏è"
    description               = "I like to dabble with things that ought to be dabbled with. üç´Ô∏èüçìÔ∏èÔ∏è"
    copyright                 = "FVCproductions"
    year                      = 2013
    og_image                  = "https://fvcproductions.com/assets/img/teaser.png"

# Permalinks
[permalinks]
  adventures                  = "/:year/:month/:day/:title/"
  blog                        = "/blog/:year/:month/:day/:title/"
  portfolio                   = "/portfolio/:year/:month/:day/:title/"

# Social Links
[social]
    # amazon                  = "AGCK4BOZOTAMEA4HTNM2DF7AL4RA"
    angellist                 = "fvcproductions"
    # behance                 = "fvcproductions"
    calendly                  = "fvcproductions"
    # codepen                 = "fvcproductions"
    # deviantart              = "fvcproductions"
    # dribbble                = "fvcproductions"
    email                     = "hello@fvcproductions.com"
    # etsy                    = "fvcproductions"
    # facebook                = "fvcproductions"
    # freecodecamp            = "fvcproductions"
    github                    = "fvcproductions"
    # gitlab                  = "fvcproductions"
    goodreads                 = "fvcproductions"
    # googleplus              = "fvcproductions2013"
    # hackernews              = "fvcproductions"
    # houzz                   = "fvcproductions"
    # instagram               = "fvcproductions"
    imgur                     = "fvcproductions"
    linkedin                  = "fvcproductions"
    medium                    = "@fvcproductions"
    meetup                    = "182920007"
    paypal                    = "fvcproductions"
    producthunt               = "fvcproductions"
    quora                     = "Frances-Coronel-1"
    reddit                    = "fvcproductions"
    scribd                    = "194063411/FVCproductions"
    slideshare                = "fvcproductions"
    # soundcloud              = "fvcproductions"
    # spotify                 = "fvcproductions"
    stackexchange             = "3595658/fvcproductions"
    # stackoverflow           = "3000467/fvcproductions"
    # steam                   = "fvcproductions"
    # trello                  = "fvcproductions"
    # tumblr                  = "fvcproductions2013"
    twitter                   = "fvcproductions"
    # vimeo                   = "fvcproductions"
    # wordpress               = "fvcproductions"
    # yelp                    = "E6StflkoWAutmRZ31zNTug"
    youtube                   = "fvcproductions2013"

[author]
    name                      = "Frances Coronel"
    copyright                 = "¬©Ô∏è FVCproductions"
