baseURL                       = "https://www.fvcproductions.com"
buildFuture                   = true
copyright                     = "This work is licensed under MIT."
defaultContentLanguage        = "en"
disqusShortname               = "fvcproductions"
enableEmoji                   = true
enableRobotsTXT               = true
footnoteReturnLinkContents    = "‚Ü©"
googleAnalytics               = "UA-63190978-3"
languageCode                  = "en-us"
metaDataFormat                = "yaml"
Paginate                      = 6
PaginatePath                  = ""
preserveTaxonomyNames         = false
pygmentsCodefences            = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle                 = "manni"
title                         = "FVCproductions"

# RSS
[outputs]
    home                      = ["HTML", "AMP", "RSS"]
    page                      = ["HTML", "AMP"]

# Output Formats
[outputFormats]
    [outputFormats.RSS]
        mediatype             = "application/rss"
        baseName              = "feed"

# Permalinks
[permalinks]
  adventures                  = "/:year/:month/:day/:title/"

# Author
[author]
    name                      = "Frances Coronel"
    copyright                 = "¬©Ô∏è FVCproductions"
    email                     = "hello@fvcproductions.com"

# Taxonomy
[taxonomies]
    category                  = "categories"
    tag                       = "tags"

# Custom Params
[params]
    contributions             = true
    copyright                 = "FVCproductions"
    description               = "I like to dabble with things that ought to be dabbled with."
    github                    = "fvcproductions/hugoma-theme"
    headline                  = "Hey there, I'm Frances! üëãüèΩÔ∏è"
    logo                      = "https://www.fvcproductions.com/assets/img/logo.png"
    og_image                  = "https://www.fvcproductions.com/assets/img/teaser.png"
    one_signal_id             = "e64fce8d-6d54-4434-8b76-3fde80e6bdf1"
    search_url                = "https://www.fvcproductions.com/search/#gsc.tab=0&gsc.q={search_term_string}"
    year                      = 2013

# Social Links
[social]
    amazon                    = "AGCK4BOZOTAMEA4HTNM2DF7AL4RA"
    angellist                 = "fvcproductions"
    behance                   = "fvcproductions"
    calendly                  = "fvcproductions"
    codepen                   = "fvcproductions"
    deviantart                = "fvcproductions"
    dribbble                  = "fvcproductions"
    email                     = "hello@fvcproductions.com"
    etsy                      = "fvcproductions"
    facebook                  = "frances.v.coronel"
    freecodecamp              = "fvcproductions"
    github                    = "fvcproductions"
    gitlab                    = "fvcproductions"
    goodreads                 = "fvcproductions"
    google_plus               = "+fvcproductions2013"
    hackernews                = "fvcproductions"
    houzz                     = "fvcproductions"
    imgur                     = "fvcproductions"
    instagram                 = "fvcproductions"
    linkedin                  = "fvcproductions"
    medium                    = "@fvcproductions"
    meetup                    = "182920007"
    paypal                    = "fvcproductions"
    producthunt               = "fvcproductions"
    quora                     = "Frances-Coronel-1"
    reddit                    = "fvcproductions"
    scribd                    = "194063411/FVCproductions"
    slideshare                = "fvcproductions"
    soundcloud                = "fvcproductions"
    spotify                   = "fvcproductions"
    stackexchange             = "3595658/fvcproductions"
    stackoverflow             = "3000467/fvcproductions"
    steam                     = "fvcproductions"
    trello                    = "fvcproductions"
    tumblr                    = "fvcproductions2013"
    twitter                   = "fvcproductions"
    vimeo                     = "fvcproductions"
    wordpress                 = "fvcproductions"
    yelp                      = "E6StflkoWAutmRZ31zNTug"
    youtube                   = "+fvcproductions2013"
